export const DUMMY_TRANSACTIONS = [
  {
    title: "Grocery Shopping",
    category: "Food",
    amount: -45,
    type: "expense" as const,
    date: new Date("2026-03-25"),
    description: "Weekly groceries from supermarket",
  },
  {
    title: "Monthly Salary",
    category: "Salary",
    amount: 2000,
    type: "income" as const,
    date: new Date("2026-03-20"),
    description: "Monthly salary deposit",
  },
  {
    title: "Taxi Ride",
    category: "Transport",
    amount: -25,
    type: "expense" as const,
    date: new Date("2026-03-22"),
    description: "Ride to airport",
  },
  {
    title: "Transfer to Savings",
    category: "Transfer",
    amount: 500,
    type: "transfer" as const,
    date: new Date("2026-03-18"),
    description: "Monthly savings transfer",
  },
  {
    title: "Online Purchase",
    category: "Shopping",
    amount: -120,
    type: "expense" as const,
    date: new Date("2026-03-15"),
    description: "Electronics from Amazon",
  },
  {
    title: "Freelance Work",
    category: "Salary",
    amount: 350,
    type: "income" as const,
    date: new Date("2026-03-10"),
    description: "Web development project",
  },
];
